apiVersion: v1
kind: Namespace
metadata:
  name: oms-dev
  labels:
    app: oms
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: oms-qa
  labels:
    app: oms
    environment: qa
---
apiVersion: v1
kind: Namespace
metadata:
  name: oms-prod
  labels:
    app: oms
    environment: production
